

// Generated by scalalr bootstrap generator 2026-05-13T16:54:45.165392

package expr.Expr

object NotationInformation {
  val signature: String  = ""
  val name: String       = "Expr"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = expr.Expr.Tables.action
  val goto:       State                                   => NonTerminal => State  = expr.Expr.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = expr.Expr.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = expr.Expr.Scanner.symbolName
}



