
// Generated by scalalr bootstrap generator 2026-04-26T20:11:33.864380

package scalalr.parser.ScalaLR

object DialectInformation {
  val scalalr: String  = "flab => boot syntax => scala"
  val notation: String = "joint boot / flab"
  val name: String     = "ScalaLR"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =scalalr.parser.ScalaLR.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =scalalr.parser.ScalaLR.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =scalalr.parser.ScalaLR.Reduction.reduction
  val symbolName: Map[Symbol, String] =scalalr.parser.ScalaLR.Scanner.symbolName
}



