
// Generated by scalalr bootstrap generator 2026-05-18T14:14:24.482629

package org.sufrin.scalalr.stage1.ScalaLR

object DialectInformation {
  val scalalr: String  = "Generation: notation AST => bootstrap AST => scala"
  val notation: String = "Forgiving bootstrap notation; described in the forgiving notation"
  val name: String     = "ScalaLR"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =org.sufrin.scalalr.stage1.ScalaLR.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =org.sufrin.scalalr.stage1.ScalaLR.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =org.sufrin.scalalr.stage1.ScalaLR.Reduction.reduction
  val symbolName: Map[Symbol, String] =org.sufrin.scalalr.stage1.ScalaLR.Scanner.symbolName
}



