
// Generated by scalalr bootstrap generator 2026-04-26T15:46:23.754936

package small.Small

object DialectInformation {
  val scalalr: String  = "scalalr: scalalr.bootstrap"
  val notation: String = "dialect: bootstrap syntax; hand parsed"
  val name: String     = "Small"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =small.Small.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =small.Small.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =small.Small.Reduction.reduction
  val symbolName: Map[Symbol, String] =small.Small.Scanner.symbolName
}



