
// Generated by scalalr bootstrap generator 2026-05-23T19:13:03.945189

package small.Small

object DialectInformation {
  val scalalr: String  = "scalalr: scalalr.bootstrap"
  val notation: String = "dialect: bootstrap syntax; hand parsed"
  val name: String     = "Small"
}

object NotationInformation {
  val signature: String  = "scalalr: scalalr.bootstrap dialect: bootstrap syntax; hand parsed"
  val name: String       = "Small"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =small.Small.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =small.Small.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =small.Small.Reduction.reduction
  val symbolName: Map[Symbol, String] =small.Small.Scanner.symbolName
}



