
// Notation: stage2 generated by ScalaLR, with symbols represented uniformly
// ScalaLR translates these representations back to their source forms in all Bison outputs. 
%define lr.type canonical-lr
// Source Translation 
// T-003	ID 
// T-004	NUM 
// T-005	CODE 
// T-006	COMMENT 
// T-007	LEXICALERROR 
// T-008	`[` 
// T-009	`]` 
// T-010	`;` 
// T-011	`=` 
// T-012	`|` 
// T-013	`:` 
// T-014	`{` 
// T-015	`}` 
// T-016	`(` 
// T-017	`)` 
// T-018	`,` 
// T-019	`%path` 
// T-020	`%type` 
// T-021	`%empty` 
// T-022	`%notation` 
// T-023	`%package` 
// T-024	`%token` 
// T-025	`%left` 
// T-026	`%right` 
// T-027	`%non` 
// T-028	`%rules` 
// T-029	`%include` 
// T-030	`%prec` 
// T-031	`%tables` 
// T-032	`%dialect` 
// T-033	`%scalalr` 
// T-034	`%signature` 
// T-035	`*` 
// T-036	`?` 
// T-037	`+` 
// T-038	SEPARATOR 
// T-039	HIGH 
%token T-003 T-004 T-005 T-006 T-007 T-008 T-009 T-010 T-011 T-012 T-013 T-014 T-015 T-016 T-017 T-018 T-019 T-020 T-021 T-022 T-023 T-024 T-025 T-026 T-027 T-028 T-029 T-030 T-031 T-032 T-033 T-034 T-035 T-036 T-037
%left T-038
%left T-039
%%
T-041: T-042 T-028 T-043 T-047 T-044 // Notation = Prefix `%rules` INCLUDE Rules OPTSEPARATOR
T-042:  // Prefix = 
T-042: T-042 T-022 T-003 // Prefix = p: Prefix `%notation` ID
T-042: T-042 T-023 T-003 // Prefix = p: Prefix `%package` ID
T-042: T-042 T-019 T-003 // Prefix = p: Prefix `%path` ID
T-042: T-042 T-031 T-003 // Prefix = p: Prefix `%tables` ID
T-042: T-042 T-029 T-005 // Prefix = p: Prefix `%include` CODE
T-042: T-042 T-024 T-045 // Prefix = p: Prefix `%token` TypedTerminals
T-042: T-042 T-025 T-045 // Prefix = p: Prefix `%left` TypedTerminals
T-042: T-042 T-026 T-045 // Prefix = p: Prefix `%right` TypedTerminals
T-042: T-042 T-027 T-045 // Prefix = p: Prefix `%non` TypedTerminals
T-042: T-042 T-030 T-045 // Prefix = p: Prefix `%prec` TypedTerminals
T-042: T-042 T-032 T-003 // Prefix = p: Prefix `%dialect` ID
T-042: T-042 T-033 T-003 // Prefix = p: Prefix `%scalalr` ID
T-042: T-042 T-034 T-003 // Prefix = p: Prefix `%signature` ID
T-043: T-029 T-005 T-038 // INCLUDE = `%include` CODE SEPARATOR
T-043:  // INCLUDE = 
T-044:  // OPTSEPARATOR = 
T-044: T-038 // OPTSEPARATOR = SEPARATOR
T-045:  // TypedTerminals = 
T-045: T-046 T-045 // TypedTerminals = TypedTerminal TypedTerminals
T-046: T-003 T-013 T-058 // TypedTerminal = ID `:` Type
T-046: T-003 T-016 T-058 T-017 // TypedTerminal = ID `(` Type `)`
T-046: T-003 // TypedTerminal = ID
T-047: T-048 // Rules = Rule
T-047: T-047 T-038 T-048 // Rules = Rules SEPARATOR Rule
T-048: T-049 T-060 T-050 // Rule = LHS S_1 RHS
T-049: T-003 T-013 T-058 T-011 // LHS = ID `:` Type `=`
T-049: T-003 T-011 // LHS = ID `=`
T-050: T-051 // RHS = Production
T-050: T-051 T-012 T-050 // RHS = Production `|` RHS
T-051: T-052 T-056 T-057 // Production = Fields Action Precedence
T-052: T-021 // Fields = `%empty`
T-052: T-062 // Fields = fields: S_2
T-053: T-054 // NamedField = FIELD
T-053: T-003 T-013 T-054 // NamedField = theFieldName: ID `:` theName: FIELD
T-054: T-003 // FIELD = ID
T-054: T-016 T-052 T-017 T-055 // FIELD = `(` Fields `)` REPEAT
T-055: T-036 // REPEAT = `?`
T-055: T-035 // REPEAT = `*`
T-055: T-037 // REPEAT = `+`
T-056:  // Action = 
T-056: T-005 // Action = CODE
T-057: T-063 // Precedence = S_3
T-058: T-003 // Type = ID
T-058: T-003 T-008 T-059 T-009 // Type = ID `[` Types `]`
T-058: T-016 T-059 T-017 // Type = `(` Types `)`
T-058: T-016 T-017 // Type = `(` `)`
T-059: T-065 // Types = S_4
T-060:  // S_1 = 
T-060: T-012 // S_1 = `|`
T-061: T-053 // S_2_L = NamedField
T-061: T-061 T-053 // S_2_L = S_2_L NamedField
T-062: T-061 // S_2 = S_2_L
T-063:  // S_3 = 
T-063: T-030 T-003 // S_3 = `%prec` ID
T-064: T-058 // S_4_L = Type
T-064: T-064 T-018 T-058 // S_4_L = S_4_L `,` Type
T-065: T-064 // S_4 = S_4_L
