
// Notation: TinyFun generated by ScalaLR, with symbols represented uniformly
// ScalaLR translates these representations back to their source forms in all Bison outputs. 
%define lr.type lalr
// Source Translation 
// T-003	NUM 
// T-004	ID 
// T-005	`(` 
// T-006	`)` 
// T-007	`[` 
// T-008	`]` 
// T-009	`,` 
// T-010	LEXICALERROR 
// T-011	NL 
// T-012	QUIT 
// T-013	`#` 
// T-014	HIGH 
// T-015	`=` 
// T-016	`+` 
// T-017	`-` 
// T-018	`*` 
// T-019	`/` 
%token T-003 T-004 T-005 T-006 T-007 T-008 T-009 T-010 T-011 T-012 T-013 T-014
%right T-015
%left T-016 T-017
%left T-014
%left T-018 T-019
%%
T-021:  // loop = 
T-021: T-021 T-022 T-011 // loop = loop command NL
T-022: T-023 // command = expr
T-022: T-012 // command = QUIT
T-023: T-004 // expr = ID
T-023: T-025 // expr = number
T-023: T-004 T-015 T-023 // expr = ID `=` expr
T-023: T-023 T-018 T-023 // expr = l: expr `*` r: expr
T-023: T-023 T-016 T-023 // expr = l: expr `+` r: expr
T-023: T-023 T-019 T-023 // expr = l: expr `/` r: expr
T-023: T-023 T-017 T-023 // expr = l: expr `-` r: expr
T-023: T-005 T-023 T-006 // expr = `(` expr `)`
T-023: T-004 T-005 T-024 T-006 // expr = ID `(` exprs `)`
T-024: T-023 // exprs = expr
T-024: T-024 T-009 T-023 // exprs = exprs `,` expr
T-025: T-003 // number = NUM
T-025: T-013 T-003 // number = `#` NUM
