
// Generated by scalalr bootstrap generator 2026-06-09T18:41:23.204080

package scalalr.stage2

object DialectInformation {
  val scalalr: String  = "compatible with stage1, stage2, and stage3"
  val notation: String = "scalalr stage2-notation"
  val name: String     = "stage2"
}

object NotationInformation {
  val generated: String  = "Tue Jun 09 18:41:23 BST 2026"
  val signature: String  = "compatible with stage1, stage2, and stage3 scalalr stage2-notation"
  val name: String       = "stage2"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =scalalr.stage2.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =scalalr.stage2.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =scalalr.stage2.Reduction.reduction
  val symbolName: Map[Symbol, String] =scalalr.stage2.Scanner.symbolName
}



