

// Generated by scalalr 2026-06-09T18:31:35.581417

package scalalr.stage2

object NotationInformation {
  val generated: String  = "Tue Jun 09 18:31:35 BST 2026"
  val signature: String  = "scalalr stage2-notation compatible with stage1, stage2, and stage3"
  val name: String       = "stage2"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = scalalr.stage2.Tables.action
  val goto:       State                                   => NonTerminal => State  = scalalr.stage2.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = scalalr.stage2.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = scalalr.stage2.Scanner.symbolName
}



