

// Generated by scalalr bootstrap generator 2026-05-15T11:23:56.553045

package IfThenElse

object NotationInformation {
  val signature: String  = ""
  val name: String       = "IfThenElse"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = IfThenElse.Tables.action
  val goto:       State                                   => NonTerminal => State  = IfThenElse.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = IfThenElse.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = IfThenElse.Scanner.symbolName
}



