package org.sufrin.scalalr
package stage2

import org.sufrin.scalalr.stage2.AST._
import org.sufrin.scalalr.stage2.Generator.{bisonCounterexamples, bisonHtml, fine, numberToBisonToken, warn}
import org.sufrin.utility.SourceCode

import java.nio.file.{Files, Path}

object CodeGenerator {
  def sourceToFile(fileName: String)(sourceCode: SourceCode): Unit = writeToFile(fileName)(sourceCode.toString)

  def writeToFile(fileName: String)(text: String): Unit = {
    import java.nio.charset.StandardCharsets
    import java.nio.file.{Files, Path}
    val path = Path.of(fileName)
    println(s"Writing   $path")
    Option(path.getParent).foreach(Files.createDirectories(_))
    Files.write(
      path,
      text.getBytes(StandardCharsets.UTF_8)
    )
  }
}

class CodeGenerator(notation: Notation, symbolTables: SymbolTables) {
  import symbolTables._

  @inline def bisonToken(name: Name): String          = numberToBisonToken(nameToNumber(name))
  @inline def bisonTokenOf(symbol: Symbol): String    = bisonToken(symbol.theName)

  def bisonTokenized(production: Production): String = {
    production.symbols.map(_.theField).map(bisonToken).mkString(" ")
  }

  def sourceText(production: Production): String = {
    val prec: String = production.precedence match {
      case Some(name) => s" %prec ${(name)}"
      case None       => ""
    }
    production.symbols.map(_.toString).mkString("", " ", prec)
  }

  private lazy val encodedForBison: SourceCode = new SourceCode() {
    out(s"// Notation: ${notation.theName} generated by ScalaLR, with symbols represented uniformly")
    out(s"// ScalaLR translates these representations back to their source forms in all Bison outputs. ")
    out(s"%define lr.type ${notation.tablesType}")
    out(s"// Source Translation ")
    for {name <- declaredTerminalNames} out(s"// ${bisonToken(name)}\t${name} ")

    // TOKEN and PRIORITY SPECS
    if (autoDeclaredTerminals.nonEmpty) {
      val decl = s"%token ${autoDeclaredTerminals.map(_.theName).mkString(" ")} "
      warn(s"Automatically declared ${decl}")
      out(autoDeclaredTerminals.map(bisonTokenOf).mkString("%token ", " ", ""))
    }
    for {spec: TokenSpec <- notation.theTokens.reverse if spec.terminals.nonEmpty} {
      val prefix = spec match {
        case _: Tokens => "%token "
        case _: Left => "%left "
        case _: Right => "%right "
        case _: Nonassoc => "%nonassoc "
        case _: Prec => "%prec "
        case _ => ""
      }
      val terms: Seq[TypedTerminal] = spec.terminals
      out(terms.map(bisonTokenOf).mkString(prefix, " ", ""))
    }
    out("%%")
    // PRODUCTIONS
    for {(name, rhs) <- nonTerminalDefinition; prod <- rhs} {
      out(s"${bisonToken(name)}: ${bisonTokenized(prod)} // ${name} = ${sourceText(prod)}")
    }
    out("")
  }

  def processGrammarWithBison(fileNamePath: String): Boolean = {
    import CodeGenerator.writeToFile
    import scala.sys.process._
    writeToFile(s"$fileNamePath.y")(encodedForBison.toString)
    val output = new StringBuilder

    def escapeHtml(s: String): String =
      s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")

    def toSource(s: String, html: Boolean = false): String = {
      var report = s
      for { num <- 3 until numberToName.length } {
        val trans =  numberToName(num).toString
        report = report.replace(numberToBisonToken(num), if (html) escapeHtml(trans) else trans)
      }
      report
    }

    var lines = 0
    def logLine(line: String): Unit = {
      output.append(toSource(line) + "\n")
      lines += 1
      lines match {
        case 1 => println(s"Bison     $line")
        case 2 =>    print("Bison     generating diagnostics ")
        case _ => if (lines%10==0) print(".")
      }
    }

    val logger = ProcessLogger(line => logLine(toSource(line)))

    val htmlArg    = if (bisonHtml) List(s"--html=$fileNamePath.html") else Nil
    val counterArg = if (bisonCounterexamples) List(s"-Wcounterexamples") else Nil
    var bisonArgs  = List("bison", "-v")++htmlArg++counterArg++List(s"--xml=$fileNamePath.xml", s"--output=$fileNamePath.tab.c", s"$fileNamePath.y")

    val exit   = Process(bisonArgs).!(logger)
    val rmExit = Process(List("rm", s"$fileNamePath.tab.c")).!(logger)


    fine(s"Bison tables in ${fileNamePath}.xml")
    if (output.nonEmpty) {
      var report = output.toString()
      report = report.replace("[-Wcounterexamples]","").replace("[--Wconflicts-sr]","").replace("[--Wconflicts-rr]","")
      println()
      writeToFile(s"$fileNamePath.log")(report)
    }

    if (exit!=0) warn(s"Bison exit: $exit")
    if (rmExit!=0) warn(s"Removing .c: $rmExit")

    try {

      //println(s"Rewriting $name.output using symbolic tokens from source")
      var report: String = toSource(Files.readString(Path.of(s"$fileNamePath.output")))
      writeToFile(s"$fileNamePath.output")(report)
    } catch {
      case exn: Exception =>
        println(s"$exn\nRewriting $fileNamePath.output (for diagnostics, etc)")
    }

    if (bisonHtml) try {
      //println(s"Rewriting $name.html using symbolic tokens from source")
      var report = toSource(Files.readString(Path.of(s"$fileNamePath.html")), true)
      writeToFile(s"$fileNamePath.html")(report)
    } catch {
      case exn: Exception =>
        println(s"$exn\nRewriting $fileNamePath.output (for diagnostics, etc)")
    }

    exit==0
  }

  def generateScalaFiles(): Unit = {
    import CodeGenerator.sourceToFile
    val targetPath = s"$thePath/$theNotationName"
    if (processGrammarWithBison(targetPath)) {
      if (Generator.roseTree) sourceToFile(s"$thePath/RoseTreeReduction.scala")  (new RoseTreeReductionGenerator(notation, symbolTables))
      sourceToFile(s"$thePath/Reduction.scala")  (new ReductionGenerator(notation, symbolTables))
      sourceToFile(s"$thePath/Components.scala") (new ComponentsGenerator(notation))
      sourceToFile(s"$thePath/Tables.scala")     (new TableGenerator(targetPath, notation, symbolTables))
      sourceToFile(s"$thePath/Scanner.scala")    (new ScannerGenerator(notation, symbolTables))
    }
  }

}
