package org.sufrin.scalalr
package stage2
import org.sufrin.scalalr.stage2.AST.Notation
import org.sufrin.utility.SourceCode


class ComponentsGenerator(notation: Notation) extends SourceCode {
  val thePackage = notation.thePackage
  out(s"""
         |// Generated by scalalr bootstrap generator ${java.time.LocalDateTime.now()}
         |
         |package $thePackage
         |
         |object NotationInformation {
         |  val signature: String  = "${notation.theSignature}"
         |  val name: String       = "${notation.theName}"
         |}
         |
         |object Components extends org.sufrin.scalalr.LRParserComponents {
         |  import org.sufrin.scalalr.Action.Action
         |  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
         |  import org.sufrin.scalalr.SourceLocation
         |  type Reduce =  PartialFunction[List[Any], Any]
         |  val action:     State                                   => Terminal=>Action      = $thePackage.Tables.action
         |  val goto:       State                                   => NonTerminal => State  = $thePackage.Tables.goto
         |  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = $thePackage.Reduction.reduction
         |  val symbolName: Map[Symbol, String]                                              = $thePackage.Scanner.symbolName
         |}
         |
         |
         |
         |""".stripMargin
  )
}
