
// Generated by scalalr bootstrap generator 2026-06-02T16:38:28.408869

package expr.Expr

object DialectInformation {
  val scalalr: String  = ""
  val notation: String = ""
  val name: String     = "Expr"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =expr.Expr.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =expr.Expr.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =expr.Expr.Reduction.reduction
  val symbolName: Map[Symbol, String] =expr.Expr.Scanner.symbolName
}



