

// Generated by scalalr bootstrap generator 2026-05-14T13:50:27.843951

package scalalr.stage2

object NotationInformation {
  val signature: String  = " scalalr stage2 notation components made by stage1 or stage2"
  val name: String       = "stage2"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = scalalr.stage2.Tables.action
  val goto:       State                                   => NonTerminal => State  = scalalr.stage2.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = scalalr.stage2.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = scalalr.stage2.Scanner.symbolName
}



