
// Notation: stage2 generated by ScalaLR, with symbols represented uniformly
// ScalaLR translates these representations back to their source forms in all Bison outputs. 
%define lr.type lalr
// Source Translation 
// T-003	ID 
// T-004	NUM 
// T-005	CODE 
// T-006	COMMENT 
// T-007	LEXICALERROR 
// T-008	`[` 
// T-009	`]` 
// T-010	`;` 
// T-011	`=` 
// T-012	`|` 
// T-013	`:` 
// T-014	`{` 
// T-015	`}` 
// T-016	`(` 
// T-017	`)` 
// T-018	`,` 
// T-019	SEPARATOR 
// T-020	`%path` 
// T-021	`%type` 
// T-022	`%empty` 
// T-023	`%notation` 
// T-024	`%package` 
// T-025	`%token` 
// T-026	`%left` 
// T-027	`%right` 
// T-028	`%non` 
// T-029	`%rules` 
// T-030	`%include` 
// T-031	`%prec` 
// T-032	`%tables` 
// T-033	`%dialect` 
// T-034	`%scalalr` 
// T-035	`%signature` 
%token T-003 T-004 T-005 T-006 T-007 T-008 T-009 T-010 T-011 T-012 T-013 T-014 T-015 T-016 T-017 T-018 T-019 T-020 T-021 T-022 T-023 T-024 T-025 T-026 T-027 T-028 T-029 T-030 T-031 T-032 T-033 T-034 T-035
%%
T-037: T-038 // command = Notation
T-038: T-039 T-029 T-040 T-044 T-041 // Notation = Prefix `%rules` INCLUDE Rules OPTSEPARATOR
T-039:  // Prefix = 
T-039: T-039 T-023 T-003 // Prefix = p: Prefix `%notation` ID
T-039: T-039 T-024 T-003 // Prefix = p: Prefix `%package` ID
T-039: T-039 T-020 T-003 // Prefix = p: Prefix `%path` ID
T-039: T-039 T-032 T-003 // Prefix = p: Prefix `%tables` ID
T-039: T-039 T-030 T-005 // Prefix = p: Prefix `%include` CODE
T-039: T-039 T-025 T-042 // Prefix = p: Prefix `%token` TypedTerminals
T-039: T-039 T-026 T-042 // Prefix = p: Prefix `%left` TypedTerminals
T-039: T-039 T-027 T-042 // Prefix = p: Prefix `%right` TypedTerminals
T-039: T-039 T-028 T-042 // Prefix = p: Prefix `%non` TypedTerminals
T-039: T-039 T-031 T-042 // Prefix = p: Prefix `%prec` TypedTerminals
T-039: T-039 T-033 T-003 // Prefix = p: Prefix `%dialect` ID
T-039: T-039 T-034 T-003 // Prefix = p: Prefix `%scalalr` ID
T-039: T-039 T-035 T-003 // Prefix = p: Prefix `%signature` ID
T-040: T-030 T-005 T-019 // INCLUDE = `%include` CODE SEPARATOR
T-040:  // INCLUDE = 
T-041:  // OPTSEPARATOR = 
T-041: T-019 // OPTSEPARATOR = SEPARATOR
T-042:  // TypedTerminals = 
T-042: T-043 T-042 // TypedTerminals = TypedTerminal TypedTerminals
T-043: T-003 T-013 T-054 // TypedTerminal = ID `:` Type
T-043: T-003 T-016 T-054 T-017 // TypedTerminal = ID `(` Type `)`
T-043: T-003 // TypedTerminal = ID
T-044: T-045 // Rules = Rule
T-044: T-044 T-019 T-045 // Rules = Rules SEPARATOR Rule
T-045: T-047 T-011 T-046 T-048 // Rule = LHS `=` OptBar RHS
T-046: T-012 // OptBar = `|`
T-046:  // OptBar = 
T-047: T-003 T-013 T-054 // LHS = ID `:` Type
T-047: T-003 // LHS = ID
T-048: T-049 // RHS = Production
T-048: T-049 T-012 T-048 // RHS = Production `|` RHS
T-049: T-050 T-052 T-053 // Production = NamedFields Action Precedence
T-050: T-022 // NamedFields = `%empty`
T-050: T-051 // NamedFields = NamedField
T-050: T-051 T-050 // NamedFields = NamedField NamedFields
T-051: T-003 // NamedField = ID
T-051: T-003 T-013 T-003 // NamedField = theFieldName: ID `:` theName: ID
T-052:  // Action = 
T-052: T-005 // Action = CODE
T-053:  // Precedence = 
T-053: T-031 T-003 // Precedence = `%prec` ID
T-054: T-003 // Type = ID
T-054: T-003 T-008 T-055 T-009 // Type = ID `[` Types `]`
T-054: T-016 T-055 T-017 // Type = `(` Types `)`
T-054: T-016 T-017 // Type = `(` `)`
T-055: T-054 // Types = Type
T-055: T-054 T-018 T-055 // Types = Type `,` Types
