

// Generated by scalalr bootstrap generator 2026-05-20T16:34:33.576454

package infer.Infer

object NotationInformation {
  val signature: String  = ""
  val name: String       = "Infer"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = infer.Infer.Tables.action
  val goto:       State                                   => NonTerminal => State  = infer.Infer.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = infer.Infer.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = infer.Infer.Scanner.symbolName
}



