
// Notation: Infer generated by ScalaLR, with symbols represented uniformly
// ScalaLR translates these representations back to their source forms in all Bison outputs. 
%define lr.type lalr
// Source Translation 
// T-003	ID 
// T-004	RETURN 
// T-005	FOOTLE 
%token T-003 T-004 T-005
%%
T-007: T-003 // expr = ID
T-007: T-003 T-003 // expr = this: ID ID
