
// Generated by scalalr bootstrap generator 2026-05-13T19:18:10.711386

package small.Small

object DialectInformation {
  val scalalr: String  = "scalalr: scalalrgen -boot or -flab"
  val notation: String = "host dialect: bootstrap syntax or stage1 or stage2 syntax"
  val name: String     = "Small"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =small.Small.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =small.Small.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =small.Small.Reduction.reduction
  val symbolName: Map[Symbol, String] =small.Small.Scanner.symbolName
}



