
// Generated by scalalr bootstrap generator 2026-04-27T19:50:16.214177

package scalalr.slab.parser

object DialectInformation {
  val scalalr: String  = "slab => boot syntax => scala"
  val notation: String = "joint boot / flab"
  val name: String     = "parser"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  val action: State=>Terminal=>Action =scalalr.slab.parser.Tables.ACTIONTABLE
  val goto: State => NonTerminal => State =scalalr.slab.parser.Tables.GOTOTABLE
  val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any] =scalalr.slab.parser.Reduction.reduction
  val symbolName: Map[Symbol, String] =scalalr.slab.parser.Scanner.symbolName
}



