#!/bin/bash
ROOT=~/GitHomes/ScalaLR
echo Making parser components for slab $MODE
echo Depends on $ROOT/scripts/scalalrgen
$ROOT/scripts/scalalrgen $MODE --output=generated$MODE slab-notation.scalalr
sync=n; read -p "Install the generated components in the slab source code? [y]" sync
test "$sync" = "y" && rsync -av generated$MODE $ROOT/slab/src/main/scala/generated
if [ "$sync" = "y" ]
then
  sync=n; read -p "Rebuild the SLAB module with sbt? [y]" sync
  [ "$sync" = "y" ] && ( cd .. ; sbt "slab / clean ; slab / package")
fi


