

// Generated by scalalr 2026-05-23T18:57:19.644750

package scalalr.stage2

object NotationInformation {
  val generated: String  = s"Sat May 23 18:57:19 BST 2026"
  val signature: String  = " stage3 dialect. Compatible with stage2 or stage3"
  val name: String       = "stage2"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = scalalr.stage2.Tables.action
  val goto:       State                                   => NonTerminal => State  = scalalr.stage2.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = scalalr.stage2.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = scalalr.stage2.Scanner.symbolName
}



