package org.sufrin.scalalr

/**
 * Representation of a terminal symbol, as generated by a lexical scanner and consumed
 * by an `LRParser` automaton. Terminal symbols have `symbol` codes that are used to
 * drive the automaton. The also have `value`s that may participate in the construction of
 * the results of a parse, and participate in shift and reduce actions.
 * Punctuation symbols are represented as lexemes with "trivial" values.
 *
 */
trait Lexeme { val value: Any ; val symbol: Int }

/** (approximation to) a location in the source text being parsed */
case class SourceLocation(line: Int, col: Int) { override def toString: String = s"@$line.$col"}

/**
 * Hopefully obsolete: thrown when an automaton cannot find an appropriate result state
 * during a GoTo action. Most often the symptom of a mistake in the table generator.
 */
case class ErroneousGoto(state: Int, symbol: Int) extends Throwable


/**
 * This module provides two methods of parsing material according to a grammar specified
 * in the `scalalr` notation. The `Pull` algorithm parses until the material is accepted or the first
 * error is found. The `Push` algorithm is invoked step-by-step, with a lexeme at a time, until
 * a step yields acceptance or an error.
 *
 * The algorithms extend a common core definition, `LRParser`, that keeps track of symbols, values, states, and
 * source locations. When symbols are pushed by a SHIFT action, so are their values, the current source location and
 * the current state. A REDUCE  (trivially) calculates the starting and ending source locations, and
 * passes them to the (compiled) reduction function derived from the scalalr action expression. The ending location is
 * the source location just before the REDUCE; the starting location is the one placed on the location stack by the
 * leftmost symbol of the material being reduced.
 *
 */

object LRParser {
  type State = Int
  type Terminal = Int
  type NonTerminal = Int
  type Symbol = Int



  import Action._

  /**
   *  Abstraction of the current state of a parsing automaton. The
   *  concrete details are provided by four stacks, all of the
   *  same length.
   *
   *  {{{
   *     val symbols = new Stack[Symbol]  // shifted symbol codes
   *     val values  = new Stack[Any]     // shifted symbol values
   *     val states  = new Stack[State]   // shifted state numbers
   *     val locations = new Stack[SourceLocation] // shifted start locations
   *  }}}
   */
  sealed trait ParseState
  /** The automaton is running  */
  case object RUNNING    extends ParseState
  case object RECOVERING extends ParseState
  /** The (push) automaton is running and wants the context to
   *  provide the next input lexeme.
   *  @see step
   */
  case object NEXTSTEP extends ParseState
  /** The input so far does not conform to the grammar:  here's a diagnosis */
  case class  ERRONEOUS(diagnosis: String) extends Throwable with ParseState
  /** The automaton has accepted the input: `values` is the result of the top-level production */
  case class  ACCEPTED(values: Any) extends ParseState
  /** 
   * A result-expression has invoked the `Shortcut.Instruct(instruction)` so as to continue the parse as if from
   * the top level after obeying the given instruction
   */
  case class  INSTRUCTED(instruction: Any) extends ParseState

  /**
   * Core of both the Pull and Push parser automata.
   * @param action maps (current) state to (current) lookahead terminal to an action
   * @param goto  maps (current) state to (current top-of-stack) nonterminal to next state
   * @param reduction maps each production number to the function that maps the values on its rhs to the single value that will replace them
   * @param symbolName maps symbols to their (string) names -- used in logging
   * @param sourceLocation generates a representation of the current source location when it is called
   * @tparam Lex representation of symbols as returned by the scanner
   */
  class LRParser[Lex <: Lexeme](
                 val action: State=>Terminal=>Action,
                 val goto: State => NonTerminal => State,
                 val reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any],
                 val symbolName: Map[Symbol, String],
                 val sourceLocation: ()=>SourceLocation) {

    import collection.mutable.Stack

    val symbols = new Stack[Symbol]
    val values  = new Stack[Any]
    val states  = new Stack[State]
    val locations = new Stack[SourceLocation]
    var parseState: ParseState = RUNNING
    var logState: Boolean = false
    var attemptRecovery = false
    var logRecovery = false
    var reductionOnError = false
    var currentState = 0

    /** MUST BE IDENTICAL TO THE (UNIVERSALLY INVARIANT) BISON CODE FOR THE VIRTUAL TERMINAL SYMBOL "error" */
    val errorSymbol: Int = 1

    /**
     * Find a state on the stack of states that will shift "error"; report the `cause`
     */
    def findRecoveryState(cause: String): Boolean = {
      if (logRecovery) println(s"$cause\nFinding an error-SHIFT state:\n${mkString}")
      def cannotShiftError(state: State): Boolean = !(action(state)(errorSymbol).isInstanceOf[SHIFT])
      while (states.nonEmpty && cannotShiftError(states.top)) {
        states.pop()
        values.pop()
        symbols.pop()
        locations.pop()
      }
      if (logRecovery && states.nonEmpty) println(s"Recovered to:\n${mkString}")
      states.nonEmpty
    }

    /**
     * A rudimentary diagnostic message for use when a parse error is discovered.
     * TODO: This really should be turned over to the client to format
     * @param currentInput
     * @param currentState
     * @return
     */
    def diagnosis(currentInput: Lex, currentState: State): String = {
      val EOF = "<end of file>"
      val acceptable = (for {(symbol, name) <- symbolName if action(currentState)(symbol) != ERROR }
                            yield if (symbol==0) EOF else name).toSeq.sorted
      val oneOf      = if (acceptable.size>1) " one of: " else ": "
      def shortValue(a: Any): String = {
        val s = a match {
          case it: String => s""""${if (it.length>10) it.take(10)+"..." else it}""""
          case it: Int    => it.toString
          case it: Long   => it.toString
          case it: Float  => it.toString
          case it: Double => it.toString
          case it: Char   => s"'$it'"
          case it: Iterable[Any] => "[...]"
          case it: Product => s"${it.productPrefix}(...)"
          case _ => ""
         }
        if (s.nonEmpty) s"($s)" else ""
      }
      val topSymbols = symbols.take(6).toSeq.map(symbolName)
      val topValues  = values.take(6).map(shortValue(_)).toSeq
      val topLocs    = locations.take(6).map(_.toString)
      val context    = for { i<-0 until topLocs.length } yield s"${topSymbols(i)}${topValues(i)}${topLocs(i)}"
      val atEof      = currentInput.symbol==0
      val eofExplain = if (atEof) EOF else ""
      val where      = s"${sourceLocation()} $eofExplain"
      val contextLine = if (context.isEmpty) "" else context.mkString("  Context:", "\n         : ", "")
      s"""Syntax error at: ${where}
         |  Found: ${if (atEof) EOF else currentInput}
         |  Expecting$oneOf${acceptable.mkString(" ")}
         |  $contextLine
         |""".stripMargin
    }

    /**
     * A 3-line string describing the symbol, value, and state stacks. The latter
     * is invariantly of length one more than the others -- which are of equal length.
     * @return
     */
    def mkString: String = {
        val sys = symbols.toSeq.map(symbolName).mkString("Symbols: ", ", ", "")
        val sts = states.toSeq.map(_.toString).mkString ("States:  ", ", ", "")
        val vls = values.toSeq.map(_.toString).mkString ("Values:  ", ", ", "")
        val lox = locations.toSeq.map(_.toString).mkString ("Locations:  ", ", ", "")
        s"$sts\n$sys\n$vls\n$lox"
    }
  }



  /**
   * Parse-until accept-or-fail algorithm. The protocol is exemplified by
   * {{{
   *     val scanner = Scanner(SourceTextCursor(source))
   *     val parser  = new LRParser.Pull[Token](ACTIONTABLE, GOTOTABLE, reduction(_), ...)
   *     println(parser.run(scanner.next(_)))
   * }}}
   *
   * If the parser run terminates with `ACCEPTED(value)` then the parse was successful, and
   * the value is the parse result as specified by the composited result expressions.
   *
   */
  class Pull[Lex <: Lexeme](action: State=>Terminal=>Action,
                            goto: State => NonTerminal => State,
                            reduction: (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any],
                            symbolName: Map[Symbol,String],
                            sourceLocation: ()=>SourceLocation)
    extends LRParser[Lex](action, goto, reduction, symbolName, sourceLocation)  {

    import collection.mutable.Stack

    def run(next: () => Lex): ParseState = {
      symbols.push(0)
      values.push(())
      states.push(0)
      var location = sourceLocation()
      locations.push(location)
      var input = next()

      while (parseState == RUNNING || parseState == RECOVERING) {
        var currentState = states.top
        val act = action(currentState)(input.symbol)
        if (logState) println(s"$currentState: ${symbolName(input.symbol)}=«$input»  $act")
        act match {
          case _: GOTO => //TODO: Not really an action
            parseState = RUNNING

          case SHIFT(newState) =>
            states.push(newState)
            symbols.push(input.symbol)
            values.push(input.value)
            locations.push(location)
            input = next()
            location = sourceLocation()
            parseState = RUNNING

          case ACCEPT =>
            parseState = ACCEPTED(values(1))

          case ERROR if parseState == RECOVERING =>
            println(s"Discarded $input")
            input = next()

          case ERROR => // parseState == RUNNING
            val cause = diagnosis(input, currentState)
            if (attemptRecovery) {
              if (findRecoveryState(cause)) {
                  val SHIFT(newState) = action(states.top)(errorSymbol)
                  states.push(newState)
                  symbols.push(errorSymbol)
                  values.push(cause)
                  locations.push(location)
                  //println(s"error SHIFT($newState)")
                  if (logState) println(s"ERROR SHIFTED: ${mkString}")
                  // experiment: force a reduction (maybe)
                  if (reductionOnError)
                     action(newState)(1)  match {
                    case REDUCE(lhsSymbol, production, size) =>
                      parseState = ERRONEOUS(s"${cause}Parsing: ${symbolName(lhsSymbol)}\n")
                      var reduced: List[Any] = Nil
                      var right = location
                      var left = location
                      // pop the top "frame"
                      for {i <- 1 to size} {
                        states.pop()
                        symbols.pop()
                        reduced = values.pop() :: reduced
                        left = locations.pop()
                      }
                      // calculate the reduced "frame"
                      if (logState) println(s"REDUCE ($reduced) to ")
                      val result = reduction(left, right, production)(reduced)
                      if (logState) println(s"$result")
                      // push its reduction and symbol type
                      currentState = states.top
                      symbols.push(lhsSymbol)
                      values.push(result)
                      states.push(goto(currentState)(lhsSymbol))
                      locations.push(left)
                      // Cheat by reducing to an ACCEPTED, ERRONEOUS, or INSTRUCTED state
                      result match {
                        case ERRONEOUS(comment: String)    => parseState = ERRONEOUS(s"$cause$comment")
                        case _: ACCEPTED |  _: ERRONEOUS | _: INSTRUCTED => parseState = result.asInstanceOf[ParseState]
                        case _ =>
                      }
                    case otherwise =>
                      parseState = ERRONEOUS(diagnosis(input, currentState))
                  }
                  else { // discard symbols until one is acceptable
                    println(s"Discarded $input")
                    input = next()
                    parseState = RECOVERING
                  }
              } else  {
                parseState = ERRONEOUS(diagnosis(input, currentState))
              }
            } else {
              parseState = ERRONEOUS(diagnosis(input, currentState))
            }


          case REDUCE(lhsSymbol, production, size) =>
            var reduced: List[Any] = Nil
            var right = location
            var left = location
            // pop the top "frame"
            for {i <- 1 to size} {
              states.pop()
              symbols.pop()
              reduced = values.pop() :: reduced
              left = locations.pop()
            }
            // calculate the reduced "frame"
            if (logState) println(s"REDUCE ($reduced) to ")
            val result = reduction(left, right, production)(reduced)
            if (logState) println(s"$result")
            // push its reduction and symbol type
            currentState = states.top
            symbols.push(lhsSymbol)
            values.push(result)
            states.push(goto(currentState)(lhsSymbol))
            locations.push(left)
            parseState = RUNNING
            // Cheat by reducing to an ACCEPTED, ERRONEOUS, or INSTRUCTED state
            result match {
              case _: ACCEPTED |  _: ERRONEOUS | _: INSTRUCTED => parseState = result.asInstanceOf[ParseState]
              case _ =>
            }
        }
      }
      parseState
    }
  }

  /**
   * Build a `Push` automaton from the aggregated tables specified by `components` and a `sourceLocation()` function
   */
  object Push {
    def apply[Token <: Lexeme](components: LRParserComponents)(sourceLocation: ()=>SourceLocation): Push[Token] = {
      import components._
      new Push(action, goto, reduction, symbolName, sourceLocation)
    }
  }

  /**
   * Build a `Pull` automaton from the aggregated tables specified by `components` and a `sourceLocation()` function
   */
  object Pull {
    def apply[Token <: Lexeme](components: LRParserComponents)(sourceLocation: ()=>SourceLocation): Pull[Token] = {
      import components._
      new Pull(action, goto, reduction, symbolName, sourceLocation)
    }
  }

  /**
   *
   * Step-by-step parse, driven externally. The protocol is exemplified here:
   * {{{
   *     val pushParser  = new LRParser.Push[Token](ACTIONTABLE, GOTOTABLE, reduction(_), ...)
   *     val pushscanner = Scanner(SourceTextCursor(source))
   *     var state = pushParser.start()
   *     while (state==LRParser.NEXTSTEP) {
   *       state = pushParser.step(pushscanner.next())
   *       println(state)
   *     }
   *     state match {
   *        case ERROR(diagnosis) => report the error, etc. and bail
   *        case ACCEPTED(value)  => use the value
   *     }
   * }}}
   *
   * Each parse `step` is invoked with the next input symbol of the material to be parsed. If
   * it terminates with `NEXTSTEP` then the parse can be continued (by invoking `step` again).
   * If `step` terminates with ACCEPTED(value)` then the parse has been successful, and
   * the  `value` is the parse result as specified by the action expressions.
   *
   */
  class Push[Lex <: Lexeme](action:     State=>Terminal=>Action,
                            goto:       State => NonTerminal => State,
                            reduction:  (SourceLocation, SourceLocation, State) => PartialFunction[List[Any], Any],
                            symbolName: Map[Symbol,String],
                            sourceLocation: ()=> SourceLocation)
    extends LRParser[Lex](action, goto, reduction, symbolName, sourceLocation)  {

    import collection.mutable.Stack

    /**
     * Initial automaton state
     */
    def start(): ParseState = {
      symbols.push(0)
      values.push(())
      states.push(0)
      val location = sourceLocation()
      locations.push(location)
      NEXTSTEP
    }

    /**
     * Move automaton to its next state by inputting `input`. The result
     * is the `ParseState` that is the outcome of this single input step.
     *
     * @param input
     */
    def step(input: Lex, location: SourceLocation=sourceLocation()): ParseState = {
      var stepUnfinished = true
      while (stepUnfinished) {
        var currentState = states.top
        var act = action(currentState)(input.symbol)
        stepUnfinished = false
        act match {
          case _: GOTO => //TODO: Not really an action
          case SHIFT(newState) =>
            states.push(newState)
            symbols.push(input.symbol)
            values.push(input.value)
            locations.push(location)
            parseState = NEXTSTEP
          case ACCEPT =>
            parseState = ACCEPTED(values(1))
          case ERROR =>
            val cause = diagnosis(input, currentState)
            if (attemptRecovery && findRecoveryState(cause)) {
              val SHIFT(newState) = action(states.top)(errorSymbol)
              states.push(newState)
              symbols.push(errorSymbol)
              values.push(None)
              locations.push(location)
              //println(s"error SHIFT($newState)")
              parseState = NEXTSTEP
            } else  {
              parseState = ERRONEOUS(diagnosis(input, currentState))
            }

          case REDUCE(lhsSymbol, production, size) =>
            var reduced: List[Any] = Nil
            var left, right: SourceLocation = location
            // pop the top "frame"
            for {i <- 1 to size} if (states.nonEmpty) {
              states.pop()
              symbols.pop()
              reduced = values.pop() :: reduced
              if (locations.nonEmpty)
                 left = locations.pop()
            }
            // calculate the reduced "frame"
            val result = reduction(left, right, production)(reduced)
            // push its reduction and symbol type
            currentState = states.top
            symbols.push(lhsSymbol)
            values.push(result)
            locations.push(left)
            val newState = goto(currentState)(lhsSymbol)
            states.push(newState)
            stepUnfinished = true
            // Cheat by reducing to an ACCEPTED, ERRONEOUS, or INSTRUCTED state
            result match {
              case _: ACCEPTED |  _: ERRONEOUS | _: INSTRUCTED => parseState = result.asInstanceOf[ParseState]
              case _ =>
            }
        }
        if (logState) Console.println(s"$currentState: «$input» $act")
      }
      parseState
    }
  }
}

/**
 * Supports short-cut termination or continuation of a parse, and should be used
 * with great discretion.
 *
 * A production that returns a `Shortcut.Shortcut` result is signalling one
 * of four outcomes:
 * {{{
 *   Accept(aValue) -- terminate the parse successfully now, yielding `aValue`
 *   Error(aString) -- terminate the parse erroneously now, yielding `aString`
 *   Continue -- continue the parse
 *   Instruct(anInstruction) -- continue the parse after having obeyed `anInstruction`
 * }}}
 * The exact interpretations of "terminate" and "continue" (and instructions) are
 * left open to be decided by specific notation/top-level combinations.
 * Some (conventional file-at-a-time compilers) will not use shortcuts at all;
 * others (for example interactive systems that incrementally act on top-level phrases
 * may use "Continue", and "Instruct" and restart the parse using the prevailing scanner)
 */
object Shortcut {
  import LRParser._
  type Shortcut = ParseState
  def  Accept(value: Any):          Shortcut = ACCEPTED(value)
  def  Instruct(instruction: Any):  Shortcut = INSTRUCTED(instruction)
  def  Error(culprit: String):      Shortcut = ERRONEOUS(culprit)
  val  Continue:                    Shortcut = RUNNING
}
