package org.sufrin.scalalr
package stage2
import org.sufrin.scalalr.stage2.AST.Notation
import org.sufrin.utility.SourceCode


class ComponentsGenerator(notation: Notation) extends SourceCode {
  val thePackage = notation.thePackage
  out(s"""
         |// Generated by scalalr ${java.time.LocalDateTime.now()}
         |
         |package $thePackage
         |
         |object NotationInformation {
         |  val generated: String  = "${new java.util.Date()}"
         |  val signature: String  = "${notation.theSignature.trim}"
         |  val name: String       = "${notation.theName}"
         |}
         |
         |object Components extends org.sufrin.scalalr.LRParserComponents {
         |  type Token = $thePackage.Scanner.Token
         |  import org.sufrin.scalalr.Action.Action
         |  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
         |  import org.sufrin.scalalr.SourceLocation
         |  type Reduce =  PartialFunction[List[Any], Any]
         |  val action:     State                                   => Terminal=>Action      = $thePackage.Tables.action
         |  val goto:       State                                   => NonTerminal => State  = $thePackage.Tables.goto
         |  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = $thePackage.Reduction.reduction
         |  // maps the integer code of a symbol to its name
         |  val symbolName: Map[Symbol, String]                                              = $thePackage.Scanner.symbolName
         |  // maps the name of a non-value-carrying "punctuation" `Token` to the token itself (useful for lexer table initialization)
         |  val symbolToken: collection.immutable.Map[String, Token]                         = $thePackage.Scanner.symbolToken
         |
         |}
         |
         |
         |
         |""".stripMargin
  )
}
