
// Notation: stage2 generated by ScalaLR, with symbols represented uniformly
// ScalaLR translates these representations back to their source forms in all Bison outputs. 
%define lr.type lalr
// Source Translation 
// T-003	ID 
// T-004	NUM 
// T-005	CODE 
// T-006	COMMENT 
// T-007	LEXICALERROR 
// T-008	`[` 
// T-009	`]` 
// T-010	`;` 
// T-011	`=` 
// T-012	`|` 
// T-013	`:` 
// T-014	`{` 
// T-015	`}` 
// T-016	`(` 
// T-017	`)` 
// T-018	`,` 
// T-019	SEPARATOR 
// T-020	`%path` 
// T-021	`%type` 
// T-022	`%empty` 
// T-023	`%notation` 
// T-024	`%package` 
// T-025	`%token` 
// T-026	`%left` 
// T-027	`%right` 
// T-028	`%non` 
// T-029	`%rules` 
// T-030	`%include` 
// T-031	`%prec` 
// T-032	`%tables` 
// T-033	`%dialect` 
// T-034	`%scalalr` 
// T-035	`%signature` 
// T-036	`*` 
// T-037	`?` 
// T-038	`+` 
%token T-003 T-004 T-005 T-006 T-007 T-008 T-009 T-010 T-011 T-012 T-013 T-014 T-015 T-016 T-017 T-018 T-019 T-020 T-021 T-022 T-023 T-024 T-025 T-026 T-027 T-028 T-029 T-030 T-031 T-032 T-033 T-034 T-035 T-036 T-037 T-038
%%
T-040: T-041 T-029 T-042 T-045 T-059 // Notation = Prefix `%rules` INCLUDE Rules S_1
T-041:  // Prefix = 
T-041: T-041 T-023 T-003 // Prefix = p: Prefix `%notation` ID
T-041: T-041 T-024 T-003 // Prefix = p: Prefix `%package` ID
T-041: T-041 T-020 T-003 // Prefix = p: Prefix `%path` ID
T-041: T-041 T-032 T-003 // Prefix = p: Prefix `%tables` ID
T-041: T-041 T-030 T-005 // Prefix = p: Prefix `%include` CODE
T-041: T-041 T-025 T-043 // Prefix = p: Prefix `%token` TypedTerminals
T-041: T-041 T-026 T-043 // Prefix = p: Prefix `%left` TypedTerminals
T-041: T-041 T-027 T-043 // Prefix = p: Prefix `%right` TypedTerminals
T-041: T-041 T-028 T-043 // Prefix = p: Prefix `%non` TypedTerminals
T-041: T-041 T-033 T-003 // Prefix = p: Prefix `%dialect` ID
T-041: T-041 T-034 T-003 // Prefix = p: Prefix `%scalalr` ID
T-041: T-041 T-035 T-003 // Prefix = p: Prefix `%signature` ID
T-042: T-030 T-005 T-019 // INCLUDE = `%include` CODE SEPARATOR
T-042:  // INCLUDE = 
T-043:  // TypedTerminals = 
T-043: T-044 T-043 // TypedTerminals = TypedTerminal TypedTerminals
T-044: T-003 T-013 T-057 // TypedTerminal = ID `:` Type
T-044: T-003 T-016 T-057 T-017 // TypedTerminal = ID `(` Type `)`
T-044: T-003 // TypedTerminal = ID
T-045: T-046 // Rules = Rule
T-045: T-045 T-019 T-046 // Rules = Rules SEPARATOR Rule
T-046: T-048 T-011 T-047 T-049 // Rule = LHS `=` OptBar RHS
T-047: T-060 // OptBar = S_2
T-048: T-003 T-013 T-057 // LHS = ID `:` Type
T-048: T-003 // LHS = ID
T-049: T-050 // RHS = Production
T-049: T-050 T-012 T-049 // RHS = Production `|` RHS
T-050: T-051 T-055 T-056 // Production = NamedFields Action Precedence
T-051: T-062 // NamedFields = fields: S_3
T-052: T-053 // NamedField = FIELD
T-052: T-003 T-013 T-053 // NamedField = theFieldName: ID `:` theName: FIELD
T-053: T-003 // FIELD = ID
T-053: T-016 T-051 T-017 T-054 // FIELD = `(` NamedFields `)` REPEAT
T-054: T-037 // REPEAT = `?`
T-054: T-036 // REPEAT = `*`
T-054: T-038 // REPEAT = `+`
T-055:  // Action = 
T-055: T-005 // Action = CODE
T-056: T-063 // Precedence = S_4
T-057: T-003 // Type = ID
T-057: T-003 T-008 T-058 T-009 // Type = ID `[` Types `]`
T-057: T-016 T-058 T-017 // Type = `(` Types `)`
T-057: T-016 T-017 // Type = `(` `)`
T-058: T-065 // Types = S_5
T-059:  // S_1 = 
T-059: T-019 // S_1 = SEPARATOR
T-060:  // S_2 = 
T-060: T-012 // S_2 = `|`
T-061: T-052 // S_3_L = NamedField
T-061: T-061 T-052 // S_3_L = S_3_L NamedField
T-062: T-061 // S_3 = S_3_L
T-063:  // S_4 = 
T-063: T-031 T-003 // S_4 = `%prec` ID
T-064: T-057 // S_5_L = Type
T-064: T-064 T-018 T-057 // S_5_L = S_5_L `,` Type
T-065: T-064 // S_5 = S_5_L
