

// Generated by scalalr 2026-05-30T12:15:47.905847

package tinyfun

object NotationInformation {
  val generated: String  = "Sat May 30 12:15:47 BST 2026"
  val signature: String  = ""
  val name: String       = "TinyFun"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = tinyfun.Tables.action
  val goto:       State                                   => NonTerminal => State  = tinyfun.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = tinyfun.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = tinyfun.Scanner.symbolName
}



