

// Generated by scalalr bootstrap generator 2026-05-21T13:45:14.462633

package tinyfun

object NotationInformation {
  val signature: String  = ""
  val name: String       = "TinyFun"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = tinyfun.Tables.action
  val goto:       State                                   => NonTerminal => State  = tinyfun.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = tinyfun.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = tinyfun.Scanner.symbolName
}



