

// Generated by scalalr bootstrap generator 2026-05-15T11:23:47.740636

package SAB

object NotationInformation {
  val signature: String  = ""
  val name: String       = "SAB"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = SAB.Tables.action
  val goto:       State                                   => NonTerminal => State  = SAB.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = SAB.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = SAB.Scanner.symbolName
}



