
// Notation: SAB generated by ScalaLR, with symbols represented uniformly
// ScalaLR translates these representations back to their source forms in all Bison outputs. 
%define lr.type lalr
// Source Translation 
// T-003	a 
%token T-003
%%
T-005: T-006 // S = A
T-005: T-007 // S = B
T-006: T-003 // A = a
T-007: T-003 // B = a
