

// Generated by scalalr 2026-06-02T16:34:42.733408

package small.Small

object NotationInformation {
  val generated: String  = "Tue Jun 02 16:34:42 BST 2026"
  val signature: String  = "host dialect: bootstrap syntax or stage1 or stage2 syntax"
  val name: String       = "Small"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = small.Small.Tables.action
  val goto:       State                                   => NonTerminal => State  = small.Small.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = small.Small.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = small.Small.Scanner.symbolName
}



