
// Notation: Small generated by ScalaLR, with symbols represented uniformly
// ScalaLR translates these representations back to their source forms in all Bison outputs. 
%define lr.type lalr
// Source Translation 
// T-003	ID 
// T-004	`;` 
// T-005	LEXICALERROR 
%token T-003 T-004 T-005
%%
T-007: T-008 // top = ids
T-008: T-009 // ids = idList
T-009: T-003 // idList = ID
T-009: T-009 T-004 T-003 // idList = idList `;` ID
