

// Generated by scalalr bootstrap generator 2026-05-13T19:18:11.186725

package small.Small

object NotationInformation {
  val signature: String  = " host dialect: bootstrap syntax or stage1 or stage2 syntax scalalr: scalalrgen -boot or -flab"
  val name: String       = "Small"
}

object Components extends org.sufrin.scalalr.LRParserComponents {
  import org.sufrin.scalalr.Action.Action
  import org.sufrin.scalalr.LRParser.{NonTerminal, State, Symbol, Terminal}
  import org.sufrin.scalalr.SourceLocation
  type Reduce =  PartialFunction[List[Any], Any]
  val action:     State                                   => Terminal=>Action      = small.Small.Tables.action
  val goto:       State                                   => NonTerminal => State  = small.Small.Tables.goto
  val reduction:  (SourceLocation, SourceLocation, State) => Reduce                = small.Small.Reduction.reduction
  val symbolName: Map[Symbol, String]                                              = small.Small.Scanner.symbolName
}



